[package]
name = "anonymous-chat-server"
version = "0.1.0"
authors = ["Jonathan Cary <jonathancary1@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["full"] }
